### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ivan-podgornov** [ivan-podgornov/fashion-buy#3]
- [x] #6
- [ ] #17
- [ ] сервис для создания постов в социальных сетях
- [ ] сервис для взаимодействия с заказами
- [ ] чат-бот для заказов
- [ ] сервис для списка будущих покупок
- [ ] чат-бот для будущих покупок
- [ ] сервис для работы с транзакциями
- [ ] чат-бот для транзакций
- [ ] сервис для работы с инцидентами
